messages:
    system-message: "Некоторое системное сообщение"
    config-not-fount: "файл конфигурации не найден"
    invalid-commit-structure: "некорректная структура коммита"
    no-file-commit: "отсутствует файл коммита"
    invalid-pre-receive: "отсуствует часть данных события pre-receive"
    command-not-found: "команда не найдена"
    lint-commit: "Проверка коммита: %v"
    issue: "Проблема"
    invalid-arg: "%s: не верный аргумент: %v"
    need-last-one-arg: "%s: нужен хотя бы один аргумент для %s"
    missing-arg: "%s: отсутствует аргумент: %v"
    ivalid-flag: "%s: не верный флаг '%s': %v"
    min-len: "%s: длина сообщения составляет %d, по правилам должно быть не менее %d символов"
    max-len-desc: "%s: длина составляет %d, по правилам должно быть менее %d символов"
    max-line-len-desc: "каждая %s строка должна быть менее %d символов"
    line-len: "в строке %d, %d символов"
    expects-bool: "ожидается булево значение, но получаем %#v"
    expects-int: "ожидается целое число, но получаем %#v"
    expects-string: "ожидается строка, но получаем %#v"
    expects-string-array: "ожидается список строк, но получаем %#v"
    expects-param-array: "ожидается список параметров, но получаем %#v"
    expects-key-value: "ожидается ключ-значение, но получаем %#v"
    params: "параметры"
    types: "типы"
    values: "значения"
    token: "токен"
    token-params: "токен в праметрах %v"
    types-params: "типы в праметрах %v"
    values-params: "значения в праметрах %v"
    empty-token: "токен не может быть пустым в параметре %v"
    exist-type: "'%s' должно существовать для типа '%s'"
    one-of-prefix: "'%s' должно быть одним из префиксов: %v"
rules:
    header-regex:
        error: "ошибка в регулярном выражении - %v"
        issue: "не соотвествует регулярному выражению - %v"
    footer-enum:
        issue: "Вы можете использовать один из %v"
        info: "[%s] токены не разрешены"
    footer-type-enum:
        issue: "токен нижнего колонтитула недействителен"
    scope-charset:
        issue: "тип может иметь только эти символы [%v]"
        info: "не верные символы [%v]"
    scope-enum:
        error: "пустая область не разрешена, вы можете использовать одну из %v"
        issue: "область '%s' не разрешена, вы можете использовать одну из %v"
    type-charset:
        issue: "тип может включать следующие символы [%v]"
        info: "не верные символы [%v]"
    type-enum:
        issue: "тип '%s' не допустим, можно использовать один из %v"