version: v0.10.1
formatter: default
rules:
- type-enum
- message-regex
- issue-prefix
- header-min-length
severity:
  default: error
settings:
  body-max-length:
    argument: -1
  body-max-line-length:
    argument: 720
  body-min-length:
    argument: 0
  description-max-length:
    argument: -1
  description-min-length:
    argument: 100
  footer-enum:
    argument: []
  footer-max-length:
    argument: -1
  footer-max-line-length:
    argument: 72
  footer-min-length:
    argument: 0
  footer-type-enum:
    argument: []
  header-max-length:
    argument: 300
  header-min-length:
    argument: 30
  scope-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/,
  scope-enum:
    argument: []
    flags:
      allow-empty: true
  scope-max-length:
    argument: -1
  scope-min-length:
    argument: 0
  type-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  type-enum:
    argument:
    - feat
    - fix
    - docs
    - style
    - refactor
    - perf
    - test
    - build
    - ci
    - chore
    - revert
  type-max-length:
    argument: -1
  type-min-length:
    argument: 0
  issue-prefix:
    argument: 
      template: 'T-(\d{3,})'
      min: 1000
      max: 10000000
  message-regex:
    argument: '^(feat|fix|chore|docs|test|refactor|ci|build|perf|style)(\(.{2,}\)|)\!*\:\s.{5,}\sT-\d+$'
  issue-exits:
    argument: 
      template: 'T-(\d{3,})'
      min: 1000
      max: 10000000
      checkUrl: 'https://sphere.loodsen.ru/api/task/check/%v/'
      httpMethod: 'GET'
      authorization: "Basic ${BASIC_AUTH_TOKEN}"