messages:
    system-message: "Внимание! \n Начиная с 21.04.25, заработает линтер на наименования коммитов. \n 
                    Пожалуйста, исправьте их заранее, чтобы избежать будущих проблем с CI/CD. \n 
                    \n
                    Подробнее: [https://itogo.int.loodsen.ru/page/d7307b57-dab4-4fee-965e-2b784fc85152]\n 
                    Обратную связь можно оставить в чате тут: [https://xlnk.loodsen.ru/join/chat/YTVkYTA3OTYtMjdlNy01M2M5LTlmMzEtYTcwODg5NjkxYTgzOjM2Y2Y2MjdkLWE5YTktNTg4YS04ZmY5LTVlY2VhY2Y0NTdjMDo5ZWMyZjcyMy1iYWE4LTU3ZGYtYjc0NC0xNzQxYjA4ZjAyZDg6MzBkZTFkNzAtNTU3MS01MTU2LWI5YzktODczMDkyMWQyZjI2OmN0c2xvLmxvb2RzZW4ucnU=] \n"  
    config-not-found: "файл конфигурации не найден"
    invalid-commit-structure: "некорректная структура коммита"
    no-file-commit: "отсутствует файл коммита"
    invalid-pre-receive: "отсутствует часть данных события pre-receive"
    command-not-found: "команда не найдена"
    lint-commit: "Проверка коммита: %v - %v"
    skip-merge-commit: "Пропуск коммита слияния: %v - %v"
    issue: "Проблема"
    invalid-arg: "%s: неверный аргумент: %v"
    need-last-one-arg: "%s: нужен хотя бы один аргумент для %s"
    missing-arg: "%s: отсутствует аргумент: %v"
    invalid-flag: "%s: неверный флаг '%s': %v"
    min-len: "%s: длина сообщения составляет %d, по правилам должно быть не менее %d символов"
    max-len-desc: "%s: длина составляет %d, по правилам должно быть менее %d символов"
    max-line-len-desc: "каждая %s строка должна быть менее %d символов"
    line-len: "в строке %d, %d символов"
    expects-bool: "ожидается булево значение, но получаем %#v"
    expects-int: "ожидается целое число, но получаем %#v"
    expects-string: "ожидается строка, но получаем %#v"
    expects-string-array: "ожидается список строк, но получаем %#v"
    expects-param-array: "ожидается список параметров, но получаем %#v"
    expects-key-value: "ожидается ключ-значение, но получаем %#v"
    expects-string-map: "ожидается карта строковых ключей и значений, но получаем %#v"
    params: "параметры"
    types: "типы"
    values: "значения"
    token: "токен"
    token-params: "токен в параметрах %v"
    types-params: "типы в параметрах %v"
    values-params: "значения в параметрах %v"
    empty-token: "токен не может быть пустым в параметре %v"
    exist-type: "'%s' должно существовать для типа '%s'"
    one-of-prefix: "'%s' должно быть одним из префиксов: %v"
    invalid-map-arg: "неверное значение для аргумента argument.%v - %v"
    num-too-low: "номер задачи должен быть больше %v"
    num-too-high: "номер задачи должен быть меньше %v"
    current-version: "Текущая версия: %v"
    actial-version: "Актуальная версия: %v"
    version-list-empty: "Список версий пуст" 
    total-size-mb: "Общий размер: %v Мб"
    actual-version: "Версия утилиты актуальна"
rules:
    message-regex: 
        error: "ошибка в регулярном выражении - %v"
        issue: "не соответствует регулярному выражению - %v"
    footer-enum:
        issue: "Вы можете использовать один из %v"
        info: "[%s] токены не разрешены"
    footer-type-enum:
        issue: "токен нижнего колонтитула недействителен"   
    scope-charset:
        issue: "тип может иметь только эти символы [%v]"
        info: "не верные символы [%v]"
    scope-enum:
        error: "пустая область не разрешена, вы можете использовать одну из %v"
        issue: "область '%s' не разрешена, вы можете использовать одну из %v"
    type-charset:
        issue: "тип может включать следующие символы [%v]"
        info: "не верные символы [%v]"
    type-enum:
        issue: "тип '%s' не допустим, можно использовать один из %v"
    issue-prefix:
        error: "неверный шаблон префикса задачи - %v"
        issue: "не указан номер задачи"
    issue-exits:
        error: "URL для проверки задач не указан"
        issue: "задача #%v не найдена"